### ISSUE TITLE
Rename iamfplayer

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/libiamf#102]
`iamfplayer` has a confusing name. "player" suggests it can be used to actually play the file on connected audio devices.

Really what it does is process IAMF files to wav. If a user wants to play them they should use any third-party player which supports wavs.

Usually other codec libraries which process their codec into wav files uses terms like "decode", "decoder", or "dec".

  - [opusdec](https://opus-codec.org/docs/opus-tools/opusdec.html)`
  - [FLAC/stream_decoder](https://xiph.org/flac/api/group__flac__stream__decoder.html)

I think that binary would be better named `iamfdec`, `iamfdecode`.

**Comment by yilun-zhangs** [comment]
@jwcullen
 
It makes sense to me, `iamfdec` sounds good, I will modify this~

Thanks.
