### ISSUE TITLE
Add output path argument

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/libiamf#103]
`iamfplayer` always writes the output `.wav` file to the same directory as the input `.iamf` file.

It is useful for users to be able to control this with a flag. I think it is OK to default to the current behavior if the flag is not present.

**Comment by yilun-zhangs** [comment]
@jwcullen 

Thanks for your suggestion, you idea makes it be more flexible for users.
I will improve this.

Thanks.

**Comment by yilun-zhangs** [comment]
fixed by #104
