### ISSUE TITLE
Source files have BSD 2-clause while LICENSE is BSD 3-clause clear

### ISSUE THREAD

**Issue by jzern** [AOMediaCodec/libiamf#109]
c5e438a17

For example [IAMF_OBU.c](https://github.com/AOMediaCodec/libiamf/blob/c5e438a17/code/src/iamf_dec/IAMF_OBU.c):

```
BSD 3-Clause Clear License The Clear BSD License

Copyright (c) 2023, Alliance for Open Media.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

versus [LICENSE](https://github.com/AOMediaCodec/libiamf/blob/c5e438a17/LICENSE):

```
BSD 3-Clause Clear License The Clear BSD License

Copyright (c) 2022, Alliance for Open Media

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in
the documentation and/or other materials provided with the distribution.

3. Neither the name of the Alliance for Open Media nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.


NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

There's no official license header according to [SPDX](https://spdx.org/licenses/BSD-3-Clause-Clear.html). Short SPDX headers could be used [1] [2] or something in line with other AOMedia projects like [SVT-AV1](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/ab6b443236c8af67d621ed1b9bc395538573345a/Source/API/EbSvtAv1Enc.h):

```
/*
* Copyright(c) ...
*
* This source code is subject to the terms of the BSD 3-Clause Clear License and
* the Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear License
* was not distributed with this source code in the LICENSE file, you can
* obtain it at https://www.aomedia.org/license. If the Alliance for Open
* Media Patent License 1.0 was not distributed with this source code in the
* PATENTS file, you can obtain it at https://www.aomedia.org/license/patent-license.
*/
```

[1]: https://spdx.dev/learn/handling-license-info/
[2]: https://spdx.github.io/spdx-spec/v2.3/file-tags/

**Comment by yilun-zhangs** [comment]
@hkchung72 @kr728-kim 
It seems license comment in code is not match with that in LICENSE file.
we may need to update the comments in code.

**Comment by hkchung72** [comment]
> @hkchung72 @kr728-kim It seems license comment in code is not match with that in LICENSE file. we may need to update the comments in code.

I believe it is correct to change this sentence from IAMF_OBU.c to "BSD 2-Clause Clear License The Clear BSD License".
I think it would be a good idea to ask Thomas Daede for a review.
Please add Thomas Daede as a reviewer. @tdaede

**Comment by jwcullen** [comment]
> I believe it is correct to change this sentence from IAMF_OBU.c to "BSD 2-Clause Clear License The Clear BSD License".

This project was released after https://groups.aomedia.org/g/main/message/10, so everything should be the BSD 3-Clause Clear License. `IAMF_OBU.c` and most other files in this repo should be BSD 3-Clause Clear and have appropriate text or refer to the correct license. 

I like James's suggestion of using a style inspired by other AOMedia projects:
  - [iamf-tools](https://github.com/AOMediaCodec/iamf-tools/blob/762a6c29f770b67387a105bd75ddfe77502e8c3e/iamf/common/bit_buffer_util.h#L1-L11)
  - [AVM](https://gitlab.com/AOMediaCodec/avm/-/blob/a4f037b77900cd56c28b66ac925ad822aea0bce5/aom_dsp/aom_convolve.c#L1-L11)
  - [SVT-AV1](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/ab6b443236c8af67d621ed1b9bc395538573345a/Source/API/EbSvtAv1Enc.h#L1-10)

Note even these AOM projects have minor variations (e.g. whether "www" is included, "patent" vs "patent-license" in URL).
