### ISSUE TITLE
Process AAC-LC Specific Config according to the spec

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/libiamf#119]
I noticed two issues with AAC-LC specific config where it does not comply to the referenced ISO+IEC-14496-1:2010.

# Issue A: Use the "expandable" fields for DecoderConfigDescriptor and DecooderSpecificInfo.

Unfortunately when investigating the difference between ISO+IEC-14496-1:2010 and ISO+IEC-14496-1-1998 
(https://github.com/AOMediaCodec/iamf/issues/338) no one noticed the "expandable" keyword and associated
syntax. This keyword applies to DecoderConfigDescriptor and DecoderSpecificInfo through their inheritance of BaseDescriptor. 

§  8.3.3 defines the use of the "expandable"  keyword. It encodes a size in the bitstream using a scheme that appears to be like a big-endian version of leb128.

As of b60e7195a this field does not seem to be handled by the decoder and it is missing in the test vectors.

- Update the decoder to handle this field in both locations.
- Update the test vectors to use this field.

# Issue B: Set DecoderConfigDescriptor reserved field to 1.

This is more trivial because it does not shift any bits around. See [#338](https://github.com/AOMediaCodec/iamf/issues/338) which notes DecoderConfigDescriptor has a reserved field fixed at 1.

As of b60e7195a the test set has this set incorrectly to 0.

- Check the decoder is OK when this field is 1.
- Update the test set to have this field be set to 1.

**Comment by tdaede** [comment]
For both issues, we will regenerate the test vectors for both v1.0.0-errata and v1.1.0 to match the spec. For issue A we will also update the decoders to match.

We will also double check other implementations (e.g. the ffmpeg implementation) to make sure they match the spec and not the old reference implementation.

**Comment by sunghee-hwang** [comment]
It can be closed as PR #118 have adressed this

**Comment by tdaede** [comment]
It has also been addressed in ffmpeg.
