### ISSUE TITLE
Test methodology to also compare pre-rendering WAV files

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/libiamf#2]
In previous meetings we have talked about that it's possible to test bit-exactness of the decoded WAV (before rendering).

James Zern also raised this question: https://groups.aomedia.org/g/WG-Storage-and-Transport/message/567

**Comment by jwcullen** [comment]
FYI #19 added these pre-rendering decoded wav files immediately after decoding with no other processing to compare against.

**Comment by sunghee-hwang** [comment]
@jwcullen @yeroro @yilun-zhangs, 
is it still an open issue or is it already addressed?

**Comment by sunghee-hwang** [comment]
It is closed as it has been addressed during the test verification.
