### ISSUE TITLE
Decoded wav files

### ISSUE THREAD

**Issue by kr728-kim** [AOMediaCodec/libiamf#20]
Could you tell us how you got the decoded wav files in PR #19?
Can the decoded wav files be used as reference waves for test verification?

**Comment by jwcullen** [comment]
The decoded wav files are the output of the blue "Decode Audio substream N" in [figure 1 section 2]( https://aomediacodec.github.io/iamf/#introduction). This file is generated by decoding each substream to a PCM then put into a .wav file immediately after decoding. Therefore there is no mixing, parameters, or any other processing applied to these files.

For a lossy codec like Opus that means this would include whatever artifacts that Opus introduces.

I think you **should** use this during test verification.
