### ISSUE TITLE
Improve human_readable_description

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/libiamf#23]
I tried understanding what the tests were about. I opened this test proto and looked at the  human_readable_description: https://github.com/AOMediaCodec/libiamf/blob/main/tests/test_000056.textproto#L5.
It says a "A variant of test_000055". test_000055 pointed me to test_000054, which pointed me to test_000050 ... and recursively I ended up in test_000004 which does not exist.

Generally, the tests should be self understandable, maybe having a list of keywords for the features they exercise would help.

**Comment by jwcullen** [comment]
I'm planning on adding an additional field to tag the section number being tested and filling it in for all existing test vectors. We'll make the descriptions specified completely without recursion. I think this will help to create a CSV-type report and sorting on the tested section numbers will at least give an overview of coverage. Some kind of deeper coverage report is not something I have time to focus on at this time.

The test vectors are fully specified to include everything to create a complete IAMF bitstream. Many of the test vectors are trying to approximate unit tests by varying as little as possible to invoke a specific feature or behavior.

I plan to add an additional field to cover this "variant" terminology. The purpose here is that is for debugging or deeper investigation purposes that is the recommended test vector to diff against. This recommended diff will generally be intended to help show the changes required for the pseudo "unit test". But the changes described in the first paragraph should give a casual observer a better idea of "what is being tested".

**Comment by jwcullen** [comment]
We have removed nesting within the descriptions and tagged major sections and keywords that each test vector covers.
