### ISSUE TITLE
test_000036 decoded wave is not trimmed at the end

### ISSUE THREAD

**Issue by kr728-kim** [AOMediaCodec/libiamf#24]
In test_000036, `samples_to_trim_at_end` is 149, but the decoded wave is not trimmed.
Is it correct that the decoded wave has the same samples with the input wave?

**Comment by jwcullen** [comment]
It is correct. The `samples_to_trim_at_end` is acting as a loaded term. First it is applied to pad the frame. That wav file needs 149 samples to pad the final frame.

If it was greater than the amount to pad the frame it would act to shorten the wav file.
