### ISSUE TITLE
Review test_000049, test_000050, test_000052~test_000056

### ISSUE THREAD

**Issue by jingbo-marquis** [AOMediaCodec/libiamf#25]
Hello ~

Issue 1： there are no demix mode parameters and recon gain parameters in bitstream, it seems that the encoder doesn't downmix channels follows https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio

Issue 2：L&R channels switch to SL&SR channels
for example: test_000049.textproto
audio_frame_metadata {
...
substream_id_ordering: [0, 1, 2, 3] # L/R, Ls/Rs, C, LFE
...
}
the channels order should be Ls/Rs, L/R, C, LFE, 
please refer to the figure 21 in https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channelgroupgenerationrule

**Comment by jwcullen** [comment]
Issue 1: [Section 8.3.2.1](https://aomediacodec.github.io/iamf/#processing-mixpresentation-rendering-m2l) seems to allow no demix mode parameters. 

```
If demixing_info_parameter_data() is not delivered
* If the playback layout complies with loudspeaker layouts supported by [[ITU2051-3]](https://aomediacodec.github.io/iamf/#biblio-itu2051-3), use EAR Direct Speakers renderer ([[ITU2127-0]](https://aomediacodec.github.io/iamf/#biblio-itu2127-0)).
* Else if the playback layout is 3.1.2ch, use the static down-mix matrices specified in [§ 8.6.2 Static Down-mix Matrix](https://aomediacodec.github.io/iamf/#processing-downmixmatrix-static).
* Else, use implementation-specific renderer
```

My understanding is that the language for demixing parameters in [section 9.2](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio) should be informative as a way the stream could be encoded.

**Comment by jingbo-marquis** [comment]
> Issue 1: [Section 8.3.2.1](https://aomediacodec.github.io/iamf/#processing-mixpresentation-rendering-m2l) seems to allow no demix mode parameters.
> 
> ```
> If demixing_info_parameter_data() is not delivered
> * If the playback layout complies with loudspeaker layouts supported by [[ITU2051-3]](https://aomediacodec.github.io/iamf/#biblio-itu2051-3), use EAR Direct Speakers renderer ([[ITU2127-0]](https://aomediacodec.github.io/iamf/#biblio-itu2127-0)).
> * Else if the playback layout is 3.1.2ch, use the static down-mix matrices specified in [§ 8.6.2 Static Down-mix Matrix](https://aomediacodec.github.io/iamf/#processing-downmixmatrix-static).
> * Else, use implementation-specific renderer
> ```
> 
> My understanding is that the language for demixing parameters in [section 9.2](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio) should be informative as a way the stream could be encoded.

The demix mode parameter is used for reconstruction element stream， if the element only supports one channel layout, it doesn't need demix mode parameter, but if supports many channel layouts, i think it needs demix mode parameter which will be used to reconstruct element stream by loudspeaker layout. but it seems that the channels are not downmix in the scalable channel audio signal in test stream . it does not seem to follows [9.2. Scalable Channel Audio Encoding](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio) provides the Scalable Channel Audio encoding rules.

[8.3.2.1. Rendering a channel-based audio element to loudspeakers](https://aomediacodec.github.io/iamf/#processing-mixpresentation-rendering-m2l) describes rendering， not encoding and reconstruction.

**Comment by kr728-kim** [comment]
Issue 1: I agree with @jingbo-marquis that it seems not to follow scalable channel encoding.
test_0000**_decoded_substream_0.wav should be Stereo L/R (L2/R2), not L / R channels of the input multi-channel audio.

Issue 2: I agree with @yeroro.

**Comment by jingbo-marquis** [comment]
> Issue 2: This is because of the scalable channel ordering, the first layer is Stereo, which already provides L/R. Then the second layer provides the rest, which are Ls/Rs, C, LFE.
> 
> Please refer to https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channelgroupgenerationrule and https://aomediacodec.github.io/iamf/#syntax-scalable-channel-layout-config on how scalable channel layout are organized.

The first layer is stereo, but it doesn't provide L/R of input multi-channels, it should be L2/R2 channels that mixed L/R and Ls/Rs, please refer to [Figure 19](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-downmixmechanism), The second layer provides L/R, C, LFE, so i think the first layer provide Ls/Rs.

**Comment by yeroro** [comment]
About Issue #2, I think we discussed in our F2F meeting with Samsung. @sunghee-hwang can you advise on whether @jingbo-marquis or I was right?

**Comment by kr728-kim** [comment]
@jwcullen @yeroro @jingbo-marquis 
Let me clarify this issues.

If 'num_layers > 1', Scalable channel audio encoding is required following according to [9.2. Scalable Channel Audio Encoding](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio).
And, in this case, `demixing_info_parameter_data()` and `recon_gain_info_parameter_data()` may be present in the IA sequence. [[IA Simple Profile](https://aomediacodec.github.io/iamf/#profiles-simple)] [[IA Base Profile](https://aomediacodec.github.io/iamf/#profiles-base)]

For non-scalable channel audio(num_layers = 1), `demixing_info_parameter_data `and `recon_gain_info_parameter_data` should not be present in the bitstream.

Please refer to [9.2. Scalable Channel Audio Encoding](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio) and [4. Profiles](https://aomediacodec.github.io/iamf/#profiles)

Therefore, test_000049, test_000052~56 and etc should follow Scalable channel audio encoding.
Also, `demixing_info_parameter_data()` and `recon_gain_info_parameter_data()` shoud be present in the bitsteam.


As above, in the case of scalable channel audio encoding(num_layer > 1), substreams are composed of down-mixed audio channels. And ChannelGroup(CG)s are sets of the substreams.
Please refer to[ 9.2.2. Down-mix Mechanism](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-downmixmechanism) and [9.2.3. Channel Layout Generation Rule](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channellayoutgenerationrule)

For example, in the case of test_000049, substreams and CGs should be set as below.
CG#0 - substream 0: L2/R2

CG#1 - substream 1: Ls5/Rs5
        - substream 2: C
        - substream 3: LFE

In the case of test_000050, substreams and CGs should be set as below.
CG#0 - substream 0: L2/R2
CG#1 - substream 1, 2, 3: Ltf3/Rtf3, C, LFE
CG#2 - substream 4, 5: Ls5/Rs5, Lss7/Rss7
CG#3 - substream 6: Ltf4, Rtf4

To make it clearer, the comments about substream channels in txtproto should be written as the channel names in Figure 19 IA Down-mix Mechanism like above.

**Comment by sunghee-hwang** [comment]
> About Issue #2, I think we discussed and agreed in our F2F meeting with Samsung. @sunghee-hwang can you advise on whether @jingbo-marquis or I was right?

@yeroro, it should be L2/R2. Jingbo is right.

**Comment by jingbo-marquis** [comment]
> @jwcullen @yeroro @jingbo-marquis Let me clarify this issues.
> 
> If 'num_layers > 1', Scalable channel audio encoding is required following according to [9.2. Scalable Channel Audio Encoding](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio). And, in this case, `demixing_info_parameter_data()` and `recon_gain_info_parameter_data()` may be present in the IA sequence. [[IA Simple Profile](https://aomediacodec.github.io/iamf/#profiles-simple)] [[IA Base Profile](https://aomediacodec.github.io/iamf/#profiles-base)]
> 
> For non-scalable channel audio(num_layers = 1), `demixing_info_parameter_data `and `recon_gain_info_parameter_data` should not be present in the bitstream.
> 
> Please refer to [9.2. Scalable Channel Audio Encoding](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio) and [4. Profiles](https://aomediacodec.github.io/iamf/#profiles)
> 
> Therefore, test_000049, test_000052~56 and etc should follow Scalable channel audio encoding. Also, `demixing_info_parameter_data()` and `recon_gain_info_parameter_data()` shoud be present in the bitsteam.
> 
> As above, in the case of scalable channel audio encoding(num_layer > 1), substreams are composed of down-mixed audio channels. And ChannelGroup(CG)s are sets of the substreams. Please refer to[ 9.2.2. Down-mix Mechanism](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-downmixmechanism) and [9.2.3. Channel Layout Generation Rule](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channellayoutgenerationrule)
> 
> For example, in the case of test_000049, substreams and CGs should be set as below. CG#0 - substream 0: L2/R2
> 
> CG#1 - substream 1: Ls5/Rs5 - substream 2: C - substream 3: LFE
> 
> In the case of test_000050, substreams and CGs should be set as below. CG#0 - substream 0: L2/R2 CG#1 - substream 1, 2, 3: Ltf3/Rtf3, C, LFE CG#2 - substream 4, 5: Ls5/Rs5, Lss7/Rss7 CG#3 - substream 6: Ltf4, Rtf4
> 
> To make it clearer, the comments about substream channels in txtproto should be written as the channel names in Figure 19 IA Down-mix Mechanism like above.

@kr728-kim 
[9.2.5. ChannelGroup Generation Rule](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channelgroupgenerationrule)
CG #i (as called DCG, i = 2, 3, …, n): This CG contains (Ci – Ci-1) number of channels. (Ci – Ci-1) channel(s) consists of as follows:
(Si – Si-1) surround channel(s) if Si > Si-1 . When S_set = { x | Si-1 < x ≤ Si and x is an integer},
If 2 is an element of S_set, the L2 channel is contained in this CG #i.
If 3 is an element of S_set, the Center channel is contained in this CG #i.
If 5 is an element of S_set, the L5 and R5 channels are contained in this CG #i.
If 7 is an element of S_set, the Lss7 and Rss7 channels are contained in this CG #i.

it should be L5/R5 instead of  Ls5/Rs5 in GC#i. L5/R5 are L/R in multi-channels. 
 
test_000049
CG#0 - substream 0: L2/R2
CG#1 - substream 1: L5/R5 - substream 2: C - substream 3: LFE

test_000050
CG#0 - substream 0: L2/R2 
CG#1 - substream 1, 2, 3: Ltf3/Rtf3, C, LFE 
CG#2 - substream 4, 5: L5/R5, Lss7/Rss7 
CG#3 - substream 6: Ltf4, Rtf4

**Comment by kr728-kim** [comment]
@jingbo-marquis You're right. it should be L5/R5 instead of Ls5/Rs5.

**Comment by jwcullen** [comment]
As of AOMediaCodec/iamf#431 it is allowed to have them omitted to exercise default behavior. As of #40 these test vectors have been updated to utilize the default behavior and the ordering should now be accurate.

I'll close this issue in 1 week if there are no further complaints.
