### ISSUE TITLE
[test_000048] parameter_rate value seems to be strange.

### ISSUE THREAD

**Issue by yongmin-kwon** [AOMediaCodec/libiamf#28]
In test_000048 case,
16000 is used as the parameter_rate value of the mix_gain parameter.

However, the duration value of parameter_block_metadata, it seems to be set based on 48000.
(Because input file length is 24000 samples and duration is 23688)

If you have any intention, please let us know clearly.

And.. I have another question personally, do you use textproto file as an input option?, or extracting the value from encoder?, or writing it manually?(maybe not..)
I wonder how you are using protocol_buffers.
Thanks :)

**Comment by jwcullen** [comment]
You are correct. We will change `parameter_rate` for that test vector to be 48000.

--------

The textproto is an input to the encoder. The [proto](https://github.com/AOMediaCodec/libiamf/tree/main/proto) directory in this GitHub repo describes the "schema" for the input format. Protocol buffers have various libraries to parse them (see https://protobuf.dev).

The encoder uses these types of libraries to parse the textproto. It then uses these values to initialize some data such as the descriptor OBUs. Then based on the descriptor OBUs, and some other metadata input it processes the input wav files to create all the Audio Frame OBUs. It then does all the work of rendering to calculate the loudness.

This allows us to make small changes to the textproto and just rerun the encoder to create test vectors that are trying to exercise certain features. If we intend to exercise "odd" behavior or edge cases we will discuss that in the human readable sections.

I think a good way to assist in the automated validation on the decoder side would be to use the above mentioned tools to process the textproto to validate consistency.

**Comment by yongmin-kwon** [comment]
Okay. Other ambisonic cases (e.g. 000038 ~000040, 000042 ~ 000048, etc) have the same value, so please check together.

___

Thank you for explaining in detail how you are using it.

The proto files in this GitHub repo are used to write scripts with Python.

I have wonder after I visited the website.
There seems to be no C reference in the official document, is it read and used directly by the reference encoder?
