### ISSUE TITLE
[Cleanup test 000000-000056][test_000056_s.mp4] mdhd.duration value is wrong.

### ISSUE THREAD

**Issue by hkchung72** [AOMediaCodec/libiamf#31]
mdhd.duration shall be equal to (summation of stts.sample_deltas - elst.media_time).
current mdhd.duration of test_000056_s.mp4 is 240034.
the correct number of mdhd.duration is 240034 - 312(=239,722).
the number of output audio samples of test_000056_s.mp4 is same to 239,722(=240034 - 312)

**Comment by hkchung72** [comment]
There are same problems in test_000021_s, _000022_s, 000024_s, 000025_s, 000026_s, 000027_s,  000028_s
000032_s, 000033_s, 000034_s, 000035_s, 000037_s,
000045_s, 000046_s, 000048_s, 000049_s,
000050_s, 000051_s, 000052_s, 000053_s, 000054_s and 0000_55s

**Comment by jwcullen** [comment]
> mdhd.duration shall be equal to (summation of stts.sample_deltas - elst.media_time).

Is this still true after the change to the spec regarding times of trimmed frames: https://github.com/AOMediaCodec/iamf/pull/433?
