### ISSUE TITLE
[Cleanup test 000000-000056] abnormal signal when use opus coding

### ISSUE THREAD

**Issue by yongmin-kwon** [AOMediaCodec/libiamf#35]
https://github.com/AOMediaCodec/libiamf/pull/30

Hi,

I think the cases of opus coding, sample file contains strange signals.

Even though we trim as many samples as pre-skip, there is additional strange data of pre-skip size.

If trim_at_start was not operated in the decoder, there was a strange signal as twice as the size of pre-skip.
Therefore, it seems that the back part of the input signal is not included.

(test_000020~000028 etc. the cases using opus coding)

For example)
Input sample: 24000
num_samples_per_frame: 128

What I expected:
312(pre-skip) | 24000(input sample) | 8(padding for num_samples_per_frame)

What I guess:
312(??) + 312(pre-skip) | 23696(shorter than input)

Please check and correct it.

**Comment by hkchung72** [comment]
Joe,
Can you send us the opus encoded file by using ffmpeg with the your original audio file of test_000020_s.mp4, test_000020_f.mp4 and test_000020.iamf?
example) ffmpeg -i original_input.wav -c:a libopus test_000020_ffmpeg.mp4

I like to know what is encoded in the test files.

**Comment by jwcullen** [comment]
1) Was this issue related to the signal in the `test_xxxxxx_decoded_substream_y.wav` files? Or was it related to the mp4 files?

If it was related to the wav files - I recently updated many Opus decoded wav files in PR #30. Maybe these new files resolve the issue?

**Comment by yongmin-kwon** [comment]
I think it's related to the .iamf files.
The signal itself is strange, and the same problem seems to occur with mp4 files.

Can you tell us how to create decoded_substream.wav?
Do you have your own decoder?

Unlike before, the total number of samples is correct now,
but meaningless 312 samples are included at the beginning of the decoded_substream.wav files. (https://github.com/AOMediaCodec/libiamf/pull/30/commits/afe55b30415dece6fcb6802cddfb166c48c564d7)

At first, I thought that the decoder did not trim at start, but when decoder not trimmed, meaningless 624 samples came out at the beginning.
So it seems that additional data was added during encoding.

I think this condition may have occurred as the offset of the parameter block changed.

Please let me know if you have any other questions.

**Comment by yeroro** [comment]
Yes, I think we have a bug. We are fixing it.
