### ISSUE TITLE
PR #30 [Cleanup test 000000-000056] the number of samples in decoded substream wave files for tests using opus codec

### ISSUE THREAD

**Issue by kr728-kim** [AOMediaCodec/libiamf#37]
In the case of test using opus codec, the number of samples in test_0000**_decoded_substream_*.wav is as short as pre-skip.

For example, decoded substream wav file of test_000020 has 23688(=24000-312) samples instead of 24000.

Please check test_000020-28 and 32-35 and 49-56.
Thanks.

**Comment by hkchung72** [comment]
mdhd.duration of test_000020.mp4 is 24312.
I think that we need to define what is the number of output audio samples clearly.
Thanks.

**Comment by jwcullen** [comment]
I updated PR #30 with new decoded wav files. They now should contain the decoded data after trimming. So for test_000020 the wav files are 24000 samples long.

The MDHD duration issue is not addressed yet and will be tracked in #31.
