### ISSUE TITLE
[test_000000_3.iamf] the samples of last frame obu. 

### ISSUE THREAD

**Issue by jingbo-marquis** [AOMediaCodec/libiamf#41]
the last frame obu only has 64 samples, not 128. 
test_000000_3.textproto:
codec_config_metadata {
codec_config_id: 200
codec_config {
codec_id: 0x6970636d # "ipcm"
num_samples_per_frame: 128
roll_distance: 0
decoder_config_lpcm {
sample_format_flags: LPCM_LITTLE_ENDIAN
sample_size: 16
sample_rate: 16000
}
}
}

**Comment by jwcullen** [comment]
Yes, that is why this "is_valid: false" test case is supposed to fail.
