### ISSUE TITLE
Set `recon_gain_is_present_flag` to 0 when omitting Parameter Block OBUs.

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/libiamf#42]
Reported in #40 [comment](https://github.com/AOMediaCodec/libiamf/pull/40#issuecomment-1590294109).

Existing test vectors have `recon_gain_is_present_flag == 1` when there are multiple layers. Even if the parameter blocks are omitted. Instead in these cases it should be set to 0.

**Comment by sunghee-hwang** [comment]
@jwcullen @yeroro @yilun-zhangs, 
is it still an open issue or was it already addressed?
