### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/libiamf#62]
The project has several README which is great, but the main README that appears on the main page is not very clear.
Can we add a description of what the project contains? It seems that it contains only a decoder, no encoder, correct?
What are the different folders for: `code` vs `tests` vs `proto`?

I'm not sure the paragraph that says:
> The source code within this repository that implements the normative portions of the Immersive Audio Model and Formats (IAMF) specification as approved by AOM as a Final Deliverable on ____ is intended to form an IAMF Reference Implementation that may be approved as an AOM Final Deliverable. Any additional functionality within this repository, including functionality that implements non-normative portions of the IAMF specification approved as a Final Deliverable, is NOT intended to form part of this IAMF Reference Implementation.

is necessary but we should add the date of WG Approved status. Or do we want it to be the full AOM approval?

**Comment by kr728-kim** [comment]
Yes, it contains only a decoder which is in the folder `code`.
`tests` and `proto` contain files for conformance testing. I think that it would be a good idea to move the `proto` into the `tests`.

I agree that the README needs to be updated. A description of each folder should be added as well as the AOM approval date.

**Comment by jwcullen** [comment]
`tests` contain the test vectors. The test vectors are described by `.textproto` files. The "schema" for these files are all `proto/*.proto` files. 

I agree `proto` can move into `tests`. After the pending PR is merged in I can do that.
