### ISSUE TITLE
Windows builds?

### ISSUE THREAD

**Issue by ThreeDeeJay** [AOMediaCodec/libiamf#68]
Are windows binaries for iamfplayer available to download anywhere?
I'm having a hard time building it myself, not sure if I'm doing something wrong or if Github actions 2019 runner (oldest available) doesn't play nice with the VS2015 solution. Would it be possible to update the solution/project files to build in VS2019/2022 or is there a way to fix this issue?:
https://github.com/ThreeDeeJay/libiamf/actions/runs/6822966181/job/18555966846#step:8:27

**Comment by yilun-zhangs** [comment]
> Thanks @yilun-zhangs, your PR request fixed the compilation issues I was having 👍 Now the executables can be automatically released on every commit pushed like this https://github.com/ThreeDeeJay/libiamf/releases/tag/latest So I can submit [my changes](https://github.com/yilun-zhangs/libiamf/compare/main...ThreeDeeJay:libiamf:main) to the main branch if/after your PR is accepted 👌

Thanks for reporting this issue, the PR has been approved and merged,
BTW, I could not receive git message from libiamf, so sorry for late response :)
If there are any issues, please feel free to register issues.
Thanks.
