### ISSUE TITLE
Duplicate iamf_bear_api.h

### ISSUE THREAD

**Issue by trevorknight** [AOMediaCodec/libiamf#73]
I noticed there are two, slightly different versions of this file:

https://github.com/AOMediaCodec/libiamf/blob/main/code/dep_external/include/bear/iamf_bear_api.h

https://github.com/AOMediaCodec/libiamf/blame/main/code/dep_external/src/binaural/iamf2bear/iamf_bear_api.h

**Comment by yilun-zhangs** [comment]
@trevorknight 
The directory "../dep_external/src/binaural/iamf2bear" is the source code of compiling iamf2bear library which relys on bear.
iamf2bear  library will be placed into "../dep_external/lib/binaural"
The compiling of "../src" will rely on iamf2bear library, and include "../dep_external/inlcude/bear/iamf_bear_api.h"

So these 2 files have different usage. Regarding the slight difference, I will update it.
