### ISSUE TITLE
IAMF_element_renderer_render_H2B in code/src/iamf_dec/h2b_rdr.c doesn't return a value

### ISSUE THREAD

**Issue by trevorknight** [AOMediaCodec/libiamf#85]
It looks like the return value of this function is not used (IAMF_decoder.c:2623), but depending on compiler and warning setup, we can't build.  I guess it should either return void or IAMF_OK?

**Comment by trevorknight** [comment]
Oh, for what it's worth, I see that IAMF_element_renderer_render_M2B returns -1 in the equivalent case

**Comment by yilun-zhangs** [comment]
fixed in #81
