### ISSUE TITLE
Add .clang-format file and run it

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/libiamf#89]
[ code/README.md](code/README.md) refers to an external .clang-format file. We should have the .clang-format file in this repo.

Also I suspect that it has not always been run on commits. Let's just run it over this entire repo to get more consistent styling. Or at least on the non-third-party code.

**Comment by yilun-zhangs** [comment]
Before submitting, I always use clang-format command at my Linux local side, I think we can remove the sentence about '.clang-format file'.
So in readme, We just guide to use clang-format command with default configure.
How do you think about it?

**Comment by jwcullen** [comment]
I think it is still better to still provide a `.clang-format` file. Even if it is just default generated or using default settings. I think this will be more reliable if external contributors have different system setups.

When I run `clang-format` across all this repo - it produces a few modifications to first-party code. It also formats some of the third-party dependencies, but I think it is OK to keep those pristine.

**Comment by yilun-zhangs** [comment]
Thanks for your suggestion, I agree with you, one unify format configure file is more reasonable,
I have provided the config in #81
